### DISCUSSION TITLE
Use solar power to heat up the water boiler

### DISCUSSION THREAD

**Discussion by toggm** [toggm/askoheat#10] [Show and tell]
Use the auto feed-in mechanism to heat up boiler with solar energy instead of feeding it back to the grid.
For this, you have to configure a power sensor entity to track in the configuration of the integration:
![image](https://github.com/user-attachments/assets/3239376e-1670-4c7b-8f66-e6dbc0862758)

The `Invert` flag will define if the provided solar power values should get inverted. By default, askoheat expect negative values to indicate that the energy flow back to the grid.

After reconfiguring the integration, two entities should exist to be able to control the auto feed-in mode:
![image](https://github.com/user-attachments/assets/91c2dd1d-f13e-4430-9fba-581e62be06cd)

### Energy manager unit Auto feed-in buffer
This number entity provides an additional number which should be kept as a buffer of the available energy to reduce toggling on and off the heater when switching other non deferrable loads on. This number will be added to the (negative) value of the provided power sensor before sending the value to the device.

### Energy manager unit Auto feed-in
This switch enables or disables the auto feed-in mechanism by:

- Enable or disable feed-in flag on the device
- If enables, send newly calculated power values to the device if power sensors value or the buffer value changes

## Askoheat+ power level detection
The askoheat+ device auto define the level of the heater depending on the available energy fed back to the grid. Unfortunately the device doesn't calculate the initial level directly but starts with the first level and tracks if the is still power fed back to the grid. After this, the device start to continuously increase the level until power is consumed from the grid. 

### Reduce toggling on and off
This might cause toggling on and off during sunrise or sunset and let the device consume energy from the grid, even if the temperature of the water boiler is not that low. Therefore it's advice to turn off the auto feed-in during this volatile phase.

This can be achieved with two simple automations:
```yaml
alias: Turn on auto feed-in
description: ""
triggers:
  - trigger: sun
    event: sunrise
    offset: "01:00:00"
conditions: []
actions:
  - action: switch.turn_on
    target:
      entity_id: switch.askoheat_XXX_load_feedin_value_enabled
    data: {}
mode: single
```

```yaml
alias: Turn off auto feed-in
description: ""
triggers:
  - trigger: sun
    event: sunset
    offset: "-01:00:00"
conditions: []
actions:
  - action: switch.turn_off
    target:
      entity_id: switch.askoheat_XXX_load_feedin_value_enabled
    data: {}
mode: single

```
