### DISCUSSION TITLE
Track energy used

### DISCUSSION THREAD

**Discussion by toggm** [toggm/askoheat#11] [Show and tell]
The Askoheat+ device doesn't have a sensor tracking the total energy used. But as it exposes the current load, the energy used can be calculated using a Home Assistant helper [integral](https://www.home-assistant.io/integrations/integration/) to calculate the energy used.

![image](https://github.com/user-attachments/assets/357b4ff9-d634-4d88-96b1-87a8a114bd72)

## Measure used energy splitted by tariff
> [!NOTE]
> Be aware that this is only a simplified approach not splitting the energy correctly, of only partially energy consumed is covered by solar energy. For this, you would need to split the energy on the source and calculate the solar vs non-solar energy based on a model (i.e. proportional distribution, prioritized distribution)

### Provide consumption meter
To be able to track the energy consumption and split it by different tariffs, home assistant provides a [utiliy meter integration](https://www.home-assistant.io/integrations/utility_meter/). Configure an entity with the following tariffs:
- peak
- offpeak
- solar_peak
- solar_offpeak

 ### Self track tariff
To be able to track the heater load based on different tariffs (and then calculate the expenses) we first need to track different tariffs. Depending on the integration of the ac inverter those tariffs might already be provided. If not, the tariffs can be calculated based on a template sensor like following
```yaml
- sensor:
  - name: tarif
    unique_id: tarif
    state: >-
      {%- set consumption = states('sensor.power_grid') | float %}
      # sensor providing information about peak or offpeak mode. Only used if there is an offpeak tariff. Alternatively use time based approak
      {%- set tarif = states('sensor.dsmr_tarief') %}
      {%- if consumption < 0 and tarif == '0001' %}
        {{ 'solar_peak' }}
      {%- elif consumption < 0 and tarif == '0002' %}
        {{ 'solar_offpeak' }}
      {%- elif tarif == '0001' %}
        {{ 'peak' }}
      {%- elif tarif == '0002' %}
        {{ 'offpeak' }}
      {%- endif %}
```

### Switch tariff of utility_meter
At last an automation is needed to be able to select the correct tariff mode for the previously create utility meter.
```yaml
alias: Tarifwechsel Solar
description: ""
triggers:
  - entity_id:
     # template sensor or other provided sensor exposing tariff
      - sensor.tarif
    trigger: state
conditions:
  - condition: not
    conditions:
      - condition: state
        entity_id: sensor.tarif
        state: unknown
actions:
  - action: select.select_option
    target:
      entity_id:
      # Previously created utility meter
        - select.boiler_eg_energy_consumption
    data:
      option: "{{states('sensor.tarif')}}"
mode: restart
```
