### ISSUE TITLE
Integrate Emergency On/Off Button via REST-Call

### ISSUE THREAD

**Issue by toggm** [toggm/askoheat#52]
### Checklist

- [x] I have filled out the template to the best of my ability.
- [x] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [x] This issue is not a duplicate feature request of [previous feature requests](https://github.com/toggm/askoheat/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

There is no support for switch emergency mode on and off through modbus.

### Describe the solution you'd like

Provide switch to integrate emergency on/off via REST endpoint:

```
askoheat_emergency_on:
  url: http://askoheat.local/on
askoheat_emergency_off:
  url: http://askoheat.local/off
``` 

### Describe alternatives you've considered

-

### Additional context

-
